### PR TITLE
Add Slovak language

### LINKED ISSUE #104: Add Slovak language

### PR DESCRIPTION
**Pull request by filiphanes**
Closes #104

### CODE REVIEW

**Comment by laszlonemeth** [comment]
Dear Filip,

I'm very glad of your patch! I was convinced that the Slovak language had been supported, but hadn't.

I'm going to add Slovak libnumbertext support to LibreOffice 7.5, with the following locale/UI support, too:

https://wiki.documentfoundation.org/ReleaseNotes/7.5#Default_.E2.80.9Cspell_out.E2.80.9D_number_and_currency_formats

Thanks,
László

**Comment by filiphanes** [comment]
how could I test masculine, feminine, neutral patterns?

**Comment by laszlonemeth** [comment]
In command line:

~/libnumbertext$ src/spellout -p cardinal-feminine -l sk 1-10
jedna
dve
tri
štyri
päť
šesť
sedem
osem
deväť
desať

In IDE (https://numbertext.github.io/Soros.html), write cardinal-feminine in the Prefix: input box

**Comment by filiphanes** [comment]
now I see there are problems with ordinals

**Pull request merged**
