### PR TITLE
Marathi spelling corrections

### PR DESCRIPTION
**Pull request by shantanuo**
corrected as per page 16 of https://www.maharashtra.gov.in/Site/Upload/Government%20Resolutions/English/20091106130447001.pdf

### CODE REVIEW

**Review by pharmankur — COMMENTED** [review]
Now its more perfect !
Thanks for pointing out the corrections.
Secondly, even though its grammatically and phonetically correct,  just rethink of the ठ् ( पायमोड्या ठ ) character in numbers like 78 , 88, 98. In certain systems or to some users it gets rendered as crap character and user may feel its some problem or error.
Rest is all OK.

**Comment by shantanuo** [comment]
I rechecked the numbers 78, 88 and 98 and found them to be correct in my PR. 
Please merge. There are no errors.

**Review by pharmankur — APPROVED** [review]
All ok !

**Comment by pharmankur** [comment]
Ok ... Merge
Thanks for contribution !

**Comment by laszlonemeth** [comment]
Dear Shantanu and Ankur,

Next version of Numbertext library with your Marathi fixes will be released soon, integrating it with LibreOffice, too. Many thanks for your contribution!

Best regards,
László

**Pull request merged**
