### PR TITLE
[th] Fix issue with currency with 1 digit decimal

### PR DESCRIPTION
**Pull request by nicorobinhood**
Fix issue with currency with 1 digit decimal so THB1.5 should be written as "หนึ่งบาทห้าสิบสตางค์" instead of "หนึ่งบาทห้าสตางค์"

Also fix the handling of digit 1 in decimal so that the if 1 is the last digit, it should be written as "เอ็ด".  This is the same issue as 6b5fc3b so the same fix is used here.

### CODE REVIEW

**Comment by laszlonemeth** [comment]
Dear Contributor! Could you give me some reference about the correct spelling of THB 101, 202...? According to https://bz.apache.org/ooo/show_bug.cgi?id=83490, this BAHTTEXT-like spelling is wrong, or less good, than the recent one.

**Comment by nicorobinhood** [comment]
I can't read the Thai in the bug report from the mentioned link. Seems to be encoding issue.

Is [Wikipedia ](https://en.wikipedia.org/wiki/Thai_numerals#Ten_to_a_million) good enough? I couldn't find any official reference in English.

**Comment by laszlonemeth** [comment]
It's enough for me, if you are a Thai native speaker or language expert. I've made the recent conversion based on that OpenOffice.org issue, see https://github.com/Numbertext/libnumbertext/blob/master/test/thaicheck.ods, i.e. 101 is หนึ่งร้อยเอ็ด, and THB 101 is หนึ่งร้อยเอ็ดบาทถ้วน, and not 
หนึ่งร้อยหนึ่งบาทถ้วน, as in BAHTTEXT. Numbertext tries to follow the more formal written language, than the simplifications for pronunciation. If both forms are correct, we can add an extra function to support the other one, too.

**Comment by nicorobinhood** [comment]
I'm a Thai native speaker. I found this [FAQ](http://www.royin.go.th/?knowledges=%E0%B8%AB%E0%B8%99%E0%B8%B6%E0%B9%88%E0%B8%87-%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD-%E0%B9%80%E0%B8%AD%E0%B9%87%E0%B8%94-%E0%B9%95-%E0%B8%81%E0%B8%A3%E0%B8%81%E0%B8%8E%E0%B8%B2%E0%B8%84%E0%B8%A1) from Royal Society of Thailand website stating that 101 is formally and exclusively หนึ่งร้อยเอ็ด (sorry, the website is in Thai.) They are responsible for planning and regulation or Thai Language who also published the Royal Thai General System of Transcription, the official system of rendering Thai words with Latin alphabet. So I'd say this is as formal and correct as it can be.

**Comment by laszlonemeth** [comment]
Thanks for your help! I am going to update also the LibreOffice Numbertext integration with you fixes, too.

**Comment by nicorobinhood** [comment]
Glad to be of help!

**Pull request merged**
