### PR TITLE
Add Galician (gl) support

### PR DESCRIPTION
**Pull request by Gallaecio**
I did not take the time to learn the whole specification, and I am not even sure of all the x00 ordinal names, but this file based on the Spanish (es) one should serve as initial support for Galician.

### CODE REVIEW

**Comment by meixome** [comment]
Excellent contribution.

**Comment by laszlonemeth** [comment]
Adrian, many thanks for your contribution! I have updated the web demo/home page, see the line Galego on https://numbertext.github.io/index.html#testimonials

**Comment by laszlonemeth** [comment]
I fixed in commit e905fa187629bd03188c9c9af6e3ab567dbf1d9a, also add ordinal-number to support default Outline numbering with ordinal indicators. Thanks for your feedback!

(By the way, the cited Wikipedia refers the dotless version for Galician with this page: https://wikidog.xunta.gal/index.php/Escrita_dos_n%c3%bameros#N.C3.BAmeros_ordinais_e_partitivos, but I believe, if official Spanish orthography moved to use dot, Galician followed that, too.)

**Comment by Gallaecio** [comment]
I don't know whether both 1.° and 1° are allowed in Galician, as in Spanish, or only the later. My guess is the same as yours, Galician probably follows the same criteria as Portuguese and Spanish. But @meixome may know better.

**Pull request merged**
